// Command stockgen regenerates internal/project/stock_fingerprints.go: the fingerprint of every
// version of every file Gnomon has ever shipped into a project's .gnomon/ directory, read from git
// history plus the current working tree. A project file matching one of these is an unmodified
// Gnomon copy, not a project customization or project-written knowledge.
//
// Run from the repository root after changing any shipped file:
//
//	go run ./tools/stockgen
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"gnomon/internal/project"
)

// shippedDirs are every directory, past or present, whose files were copied into projects.
var shippedDirs = []string{
	"workflows", "context", "contracts", "evaluations", "decisions", "specifications", "verification", "templates",
	"internal/project/bundled",
}

func main() {
	set := map[string]map[string]bool{}
	add := func(name string, data []byte) {
		if set[name] == nil {
			set[name] = map[string]bool{}
		}
		set[name][project.Fingerprint(data)] = true
	}

	out, err := exec.Command("git", append([]string{"log", "--all", "--format=%H", "--"}, shippedDirs...)...).Output()
	if err != nil {
		fail(err)
	}
	for _, commit := range strings.Fields(string(out)) {
		files, err := exec.Command("git", append([]string{"ls-tree", "-r", "--name-only", commit, "--"}, shippedDirs...)...).Output()
		if err != nil {
			fail(err)
		}
		for _, f := range strings.Fields(string(files)) {
			if path.Ext(f) != ".md" {
				continue
			}
			data, err := exec.Command("git", "show", commit+":"+f).Output()
			if err != nil {
				fail(err)
			}
			add(path.Base(f), data)
		}
	}
	for _, dir := range shippedDirs {
		_ = filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
			if err == nil && !info.IsDir() && filepath.Ext(p) == ".md" {
				if data, rerr := os.ReadFile(p); rerr == nil {
					add(filepath.Base(p), data)
				}
			}
			return nil
		})
	}

	names := make([]string, 0, len(set))
	for n := range set {
		names = append(names, n)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/stockgen; DO NOT EDIT.\n\npackage project\n\n")
	b.WriteString("// stockFingerprints maps a shipped file's name to the fingerprint of every version Gnomon has\n// ever shipped under that name (see IsStock).\nvar stockFingerprints = map[string][]string{\n")
	for _, n := range names {
		hashes := make([]string, 0, len(set[n]))
		for h := range set[n] {
			hashes = append(hashes, h)
		}
		sort.Strings(hashes)
		fmt.Fprintf(&b, "\t%q: {\n", n)
		for _, h := range hashes {
			fmt.Fprintf(&b, "\t\t%q,\n", h)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	if err := os.WriteFile("internal/project/stock_fingerprints.go", b.Bytes(), 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "stockgen:", err)
	os.Exit(1)
}
